[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "V-Host-Factor-DB"
authors = [{name = "Nathaniel del Rosario, Elianna Kondylis, and Jacklyn Luu"}]
dynamic = ["version", "description"]
